### ISSUE TITLE
Getting this error while validating checksum. Can anyone help

### ISSUE THREAD

**Issue by aman6607** [paytm/Paytm_Node_Checksum#9]
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at Decipheriv.update (node:internal/crypto/cipher:176:11)
    at Function.decrypt (D:\MERN-STACK\server\paytm\PaytmChecksum.js:15:28)
    at Function.verifySignatureByString (D:\MERN-STACK\server\paytm\PaytmChecksum.js:56:34)
    at Function.verifySignature (D:\MERN-STACK\server\paytm\PaytmChecksum.js:47:24)
    at paytmResponse (file:///D:/MERN-STACK/server/controller/payment-controller.js:27:41)
    at Layer.handle [as handle_request] (D:\MERN-STACK\server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\MERN-STACK\server\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\MERN-STACK\server\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\MERN-STACK\server\node_modules\express\lib\router\layer.js:95:5)

**Comment by abhishekthanvi8** [comment]
@aman6607 can you explain how you fixed this ?
